src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message = "Un autre utilisateur utilise ce mail , merci de le modifier") 
 */
class User implements UserInterface 
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner un Email valid!")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /*
      * @Assert\EqualTo(propertyPath="hash", message"Vous n'avez pas confirmez votre mot de passe")
    */
    public  $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length( min=10,   max=255,  minMessage ="L'introduction doit faire plus de 10 caracteres",  maxMessage ="le titre doit faire moins de 255 caracteres ")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
    }
  /**
     * Initialisation du slug par le manage
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug() {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName." ".$this->lastName);
        }
    }

    public function getFullName() {
        return ("{$this->firstName} {$this->lastName}");
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPassword()
    {
          return $this->getHash();
    }

    public function getRoles()
    {
             return ['ROLE_USER'];
    }

    public function getSalt() {}
    public function getUsername() {
        return $this->getEmail();
    }

   public  function eraseCredentials(){}

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class UserController extends AbstractController
{
    /**
     * @Route("/user/{slug}", name="user_show")
    */
    public function index(User $user)
    {
        return $this->render('user/index.html.twig', [
              'user'=> $user
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page de {{user.fullName }}{% endblock %}

{% block body %}
    <div class="container">
     
        <div class="row align-items-center">
            <div class="col-3 ">
                
                 <img src="{{user.picture}}" alt="Avatar de {{user.fullName}}" class="avatar mb-3">
                 <br>
                    <span class="badge badge-primary">{{user.ads | length}} annonces</span>
            </div>
            <div class="col-9">
                <h1>
                    {{user.fullName}}
                </h1>
                {% if user is same as (app.user) %}
                <div class="mt-3">
                  <a href="{{ path('account_profile') }}" class ="btn btn-primary mr-2 mb-2"> Modification</a>
                  <a href="{{ path('account_password') }}" class ="btn btn-primary mr-2 mb-2"> Mot de passe </a>
                </div>
                {% endif %}

            </div>
        </div>
        {{ user.description | raw }}
        <hr>
        <h2>Les annonces de {{user.fullName}} </h2>
        {% if user.ads | length > 0 %}
        <div class="row">
            {% for ad in user.ads %}
               {% include "ad/_ad.html.twig" %}
            {% endfor %}
        </div>
        {% else %}
        <div class="alert alert.warning">
            <p>
            <strong> {{user.fullName}} n'a pas encore d'annonces sur le site </strong>
            </p>
        </div>
        {% endif %}
    </div>
{% endblock %}